spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/ragchat_dev}
    username: ${DATABASE_USERNAME:devuser}
    password: ${DATABASE_PASSWORD:devpassword}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}

app:
  security:
    api-key: ${API_KEY:dev-api-key}
    header-name: X-API-KEY
  cors:
    allowed-origins: http://localhost:3000

  llm:
    provider: groq
    api-url: https://api.groq.com/openai/v1/chat/completions
    api-key: ${GROQ_API_KEY:dev-groq-key}
    model: llama-3.1-8b-instant
    temperature: 0.7
    max-tokens: 1024
