spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}

app:
  security:
    api-key: ${API_KEY}
    header-name: X-API-KEY

  llm:
    provider: groq
    api-url: https://api.groq.com/openai/v1/chat/completions
    api-key: ${GROQ_API_KEY}
    model: llama-3.1-8b-instant
    temperature: 0.7
    max-tokens: 1024
