server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /ragchat

spring:
  application:
    name: rag-chat-storage-service

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  cache:
    type: redis
    redis:
      time-to-live: 1800s

  liquibase:
    enabled: false

app:
  rate-limiting:
    enabled: true
    requests: 100
    hours: 1
    header-name: X-RATE-LIMIT-KEY

  pagination:
    default-page-size: 20
    max-page-size: 100
    default-sort-field: "createdAt"
    default-sort-direction: "desc"

logging:
  config: classpath:logback-spring.xml

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
